__Exercise__  <br>

1. Create len(10) integer array filled with zeros

In [26]:
import numpy as np

a = np.zeros(10,int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

2. Create 3x5 floating point array filled with ones

In [27]:
a = np.ones(15,float)
a.shape = (3,5)
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

3. Create 3x5 array filled with 3.14

In [3]:
a = np.array([])
for i in range(15):
    a = np.append(a,3.14)
    
a.shape = (3,5)
a

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

4. Create an array filled with a linear space starting at 0, ending at 20, stepping by 2

In [68]:
a = np.arange(0,22,2)    #end를 22를 준 이유는 end를 20으로 주었을 경우 array가 0으로 시작해 20으로 끝나지 않기 때문입니다.
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

5. Create an array of five values evenly spaced between 0 and 1

In [34]:
a = np.linspace(0,1,5)
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

6. Create a 3x3 array of uniformly distributed random (0, 1)

In [21]:
a = np.random.uniform(0,1,size=9)
a.shape = (3,3)
a

array([[0.93481948, 0.97893643, 0.30573034],
       [0.76719548, 0.202123  , 0.52640667],
       [0.94452786, 0.38036068, 0.17692182]])

7. Create a 3x3 array of with mean 0 and standard deviation 1

In [16]:
a = np.random.normal(0,1,size = 9)
a.shape = (3,3)
print(a)

[[ 2.10789322 -1.45681418 -0.10487253]
 [ 1.13493293  1.37303775 -1.16520731]
 [-0.76814013  0.54444788  1.17974617]]


8. Create a 3x3 array of random integers in the interval [0, 10]

In [63]:
a = np.random.randint(0,10,size =9).reshape(3,3)
a

array([[0, 5, 6],
       [8, 3, 0],
       [4, 2, 9]])

9. Create a 3x3 identity matrix

In [5]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])