## 1. Logical Operators

- Logical operators, when combined with flow control, allow for complex choices to be compactly expressed.

### 1.1 >, >=, <, <=, ==, !=

- The core logical operators are

<img src="./img/9.png" width="600" height="600">

- Logical operators can be used on scalars, arrays and matrices. 
- All comparisons are done element-by-element.
- Return either True or False (Boolean).

In [1]:
import numpy as np

print(1.0 < 5.0)
print(1.0 == 5.0)
print(1.0 != 5.0)

x =  np.arange(5)
print(x<5)
x = np.array([[1,2], [-3,-4]])
y = np.array([1,-1])
print(x>y)

True
False
True
[ True  True  True  True  True]
[[False  True]
 [False False]]


### 1.2 and, or, not and xor

- Logical expressions can be combined using four logical devices,

<img src="./img/10.png" width="600" height="600">

- The keyword version (e.g. and) can only be used with scalars.
- Both the function and bitwise operators can be used with Numpy arrays.

In [2]:
print((1>2) and (3>4))
print((1>2) or (3>4))
print(~((1>2) and (3>4)))

False
False
-1


In [3]:
x = np.arange(-2,4)
(x>0) and (x<2)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [4]:
x = np.arange(-2,4)
(x>0) & (x<2)

array([False, False, False,  True, False, False])

In [5]:
x = np.arange(-2,4)
x>0 & x<2

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### 1.3 Multiple tests (all and any)
- all returns True if all logical elements in an array is True.
- any returns if any element of an array is True.

In [6]:
any([False, False, False])

False

In [7]:
any([True, False, False])

True

In [8]:
x = np.array([1,2,3,4])
x <= 2

array([ True,  True, False, False])

In [9]:
any(x<=2)

True

In [10]:
all(x<=2)

False

In [11]:
x = np.array([[1,2,3,4]])
x <= 2

array([[ True,  True, False, False]])

In [12]:
x.shape

(1, 4)

In [13]:
any(x<=2)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [36]:
(x<=2).any()

True

### 2. Flow control, Loops

- Flow control utilizes logical variables to allow different code to be executed depending on whether certain conditions are met.
- Python use white space changes to indicate the start and end of flow control blocks, and so indentation matters.
- Best practice is to only use spaces (and not tabs) and to use 4 spaces when starting a new level of indentation.

In [15]:
if 1+2==3:
    print(4)

4


## 2.1 if, elif, else

<img src="./img/11.png" width="600" height="600">


In [16]:
x=5

if x<5:
    x += 1
else :
    x -= 1
x

4

In [17]:
x=5

if x<5:
    x += 1
elif x>5:
    x -= 1
else :
    x *= 2
x

10

### 2.2 for

- for loops begin with for _item_ in _iterable_
- The generic structure of a for loop is

for _item_ in _iterable_ : 
    _Code to run_

In [18]:
count = 0
for i in range(100):
    count += i
count

4950

In [19]:
count = 0
for i in np.linspace(0,500,50):
    count += i
count

12499.999999999998

- Loops can also be nested

In [20]:
count = 0

for i in range(10) :
    for j in range(10) :
        count += j
        
count

450

- or can contain flow control variables

In [21]:
returns = np.random.rand(100)
count = 0
for ret in returns :
    if ret < 0 :
        count += 1
count

0

### 2.3 while

- while loops are useful when the number of iterations needed depends on the outcome of the loop contents.
- while loops are commonly used when a loop should only stop if a certain condition is met.

In [22]:
count = 0
i=0
while i < 10 :
    count += i
    i += 1
count

45

- while loops should generally be avoided when for loops are sufficient. 
- However, there are situations where no for loop equivalence exists.

In [23]:
mu = abs(100 * np.random.rand(1))
index = 1

while abs(mu) > 0.0001 :
    mu = (mu+np.random.randn(1))/index
    index = index+1

### 2.4 break, continue

- A loop can be terminated early using break.
- continue can be used to skip an iteration of a loop

In [24]:
x = np.random.randn(1000)
for i in x :
    print(i)
    if i > 2 :
        break

2.1427871114975434


In [25]:
x = np.random.rand(10)
for i in x:
    if i < 0 : 
        print(i)

In [26]:
x = np.random.rand(10)
for i in x:
    if i >= 0 : 
        continue
    print(i)

### 2.5 try, except

- try, except handles exceptions which are outside of the programmer's control. 
- In most numerical applications, code should be deterministicand so dangerous codes can usually be avoided. 
- When it can't (e.g. reading data from a data source which isn't always available), then try, except can be used.

In [27]:
text = ['a', '1', '54.1', '43.a']
for t in text :
    try :
        temp = float(t)
        print(temp)
    except ValueError:
        print('Not convertable to a float')

Not convertable to a float
1.0
54.1
Not convertable to a float


### 2.6 List Comprehensions

- List comprehensions are an optimized method of building a list which may simplify code when an iterable object is looped across and the results are saved to a list.

In [33]:
x = np.arange(50000)#y
x

array([    0,     1,     2, ..., 49997, 49998, 49999])

In [34]:
[np.exp(x[i]) for i in range(len(x))]

[1.0,
 2.718281828459045,
 7.38905609893065,
 20.085536923187668,
 54.598150033144236,
 148.4131591025766,
 403.4287934927351,
 1096.6331584284585,
 2980.9579870417283,
 8103.083927575384,
 22026.465794806718,
 59874.14171519782,
 162754.79141900392,
 442413.3920089205,
 1202604.2841647768,
 3269017.3724721107,
 8886110.520507872,
 24154952.7535753,
 65659969.13733051,
 178482300.96318725,
 485165195.4097903,
 1318815734.4832146,
 3584912846.131592,
 9744803446.248903,
 26489122129.84347,
 72004899337.38588,
 195729609428.83878,
 532048240601.7986,
 1446257064291.475,
 3931334297144.042,
 10686474581524.463,
 29048849665247.426,
 78962960182680.69,
 214643579785916.06,
 583461742527454.9,
 1586013452313430.8,
 4311231547115195.0,
 1.1719142372802612e+16,
 3.1855931757113756e+16,
 8.659340042399374e+16,
 2.3538526683702e+17,
 6.398434935300549e+17,
 1.739274941520501e+18,
 4.727839468229346e+18,
 1.2851600114359308e+19,
 3.4934271057485095e+19,
 9.496119420602448e+19,
 2.581312886190067